/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nekocraft.launcher;

import com.sun.servicetag.SystemEnvironment;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Administrator
 */
public class NekoUser {
    private String username;
    private String password;
    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }
    public BufferedImage getHeadImage(){
        try{
            if(!getUsername().equals("")){
            return ImageIO.read(new URL("https://nekocraft.com/api/nocdn/head/"+getUsername()).openStream());
            }
            return ImageIO.read(new URL("https://nekocraft.com/api/nocdn/head/char").openStream());
        }catch(Exception e){
            //NekoLauncher.handleException(e);
            return new BufferedImage(64,64,BufferedImage.TYPE_4BYTE_ABGR);
        }
    }
    public void saveUser(File target,boolean savePassword){
      OutputStream os=null;
        try {
            Properties prop=new Properties();
            os = new FileOutputStream(target);
            prop.setProperty("username", getUsername());
            if(savePassword){
            prop.setProperty("password", Base64Utils.getBASE64(getPassword().getBytes()));
            }else{
                prop.setProperty("password", "");
            }
            prop.store(os,"Generated by NekoLauncher.Meow~");
        } catch (Exception ex) {
            NekoLauncher.handleException(ex);
        } finally {
            try {
                os.close();
            } catch (IOException ex) {
                NekoLauncher.handleException(ex);
            }
        }
      
    }
    public void loadUser(File source){
        InputStream is = null;
        try {
            Properties prop=new Properties();
            is = new FileInputStream(source);
            prop.load(is);
            setUsername(prop.getProperty("username"));
            setPassword(new String(Base64Utils.getFromBASE64(prop.getProperty("password"))));
        } catch (Exception ex) {
            NekoLauncher.handleException(ex);
        } finally {
            try {
                is.close();
            } catch (IOException ex) {
                NekoLauncher.handleException(ex);
            }
        }
    }
}
